# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0e2ae1264a41bd7bef6b3f795c1a5834faea22a051bcb2190d889ecac5cbab5c9f1d72b93bc2b4c6df4321b90b03ca04b1af32c3401b0359ba23f9c3e9fdff1

test:
  secret_key_base: a0879cbb4c7d07ee075db3b49fcffe819e49bed9b86bea60d158d0b1a779e08f5e010d3fdb44aca00462283501e2a99c08e07236c3120c33f412b6192f8aaa1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
